(defpackage :tsinco.ast
  (:use
   :common-lisp))

(in-package :tsinco.ast)

(define-token-class
    (open-brace-token
     close-brace-token
     open-paren-token
     close-paren-token
     open-bracket-token
     close-bracket-token
     dot-token
     dot-dot-dot-token
     semicolon-token
     comma-token
     less-than-token
     less-than-slash-token
     greater-than-token
     less-than-equals-token
     greater-than-equals-token
     equals-equals-token
     exclamation-equals-token
     equals-equals-equals-token
     exclamation-equals-equals-token
     equals-greater-than-token
     plus-token
     minus-token
     asterisk-token
     asterisk-asterisk-token
     slash-token
     percent-token
     plus-plus-token
     minus-minus-token
     less-than-less-than-token
     greater-than-greater-than-token
     greater-than-greater-than-greater-than-token
     ampersand-token
     bar-token
     caret-token
     exclamation-token
     tilde-token
     ampersand-ampersand-token
     bar-bar-token
     question-token
     colon-token
     at-token
     backtick-token
     equals-token
     plus-equals-token
     minus-equals-token
     asterisk-equals-token
     asterisk-asterisk-equals-token
     slash-equals-token
     percent-equals-token
     less-than-less-than-equals-token
     greater-than-greater-than-equals-token
     greater-than-greater-than-greater-than-equals-token
     ampersand-equals-token
     bar-equals-token
     caret-equals-token
     dotdot-token 
     question-token 
     exclamation-token 
     colon-token 
     equals-token 
     asterisk-token 
     equals-greater-than-token 
     end-of-file-token 
     readonly-token 
     await-keyword-token))

(define-token-class (abstract-keyword
                     async-keyword
                     const-keyword
                     declare-keyword
                     default-keyword
                     export-keyword
                     public-keyword
                     private-keyword
                     protected-keyword
                     readonly-keyword
                     static-keyword))

